##Puedes agregar el nombre de los servidores que actuaran como lobby y agregarlos
## en la lista, recuerda que deben ser los mismos que en el archivo config.yml del Bungee.

config:
  countdown: "true"
  time: "3"
  lobbys:
  commands:
    lobby:
      command: "lobby"
      permission: "lobby.use"
      aliases:
        - "hub"
        - "leave"
<<<<<<< HEAD
      denied_servers:
=======
      denied_servers:
>>>>>>> 748888d96e61c96841c703bafcc436b3cb3b2e52
