##Puedes agregar el nombre de los servidores que actuaran como lobby y agregarlos
## en la lista, recuerda que deben ser los mismos que en el archivo config.yml del Bungee.

config:
  countdown: "true"
  time: "3"
  lobbys:
  commands:
    lobby:
      command: "lobby"
      permission: "lobby.use"
      aliases:
        - "hub"
        - "leave"
      denied_servers:
