##Puedes agregar el nombre de los servidores que actuaran como lobby y agregarlos
## en la lista, recuerda que deben ser los mismos que en el archivo config.yml del Bungee.

config:
  countdown: "true"
  time: "3"
  ## tp_mode:
  #You can set the tp_mode between: "random" , "lessplayers"
  #random: Players will be teleported randomly to any lobby.
  #lessplayers: Players will be teleported to the lobby with less players on the server.
  tp_mode: "lessplayers"
  lobbys:
  commands:
    lobby:
      command: "lobby"
      permission: "lobby.use"
      aliases:
        - "hub"
        - "leave"
      denied_servers: